export 'movies/movies_providers.dart';
export 'movies/movies_repository.dart';
export 'movies/movies_slideshow_provider.dart';
export 'movies/inicial_loading_provider.dart';
export 'actors/actor_repository_provider.dart';
export 'actors/actors_by_movie_provider.dart';
export 'movies/movie_info_provider.dart';
export 'search/search_movie_provider.dart';
export 'storange/local_storange_provider.dart';
